theme: jekyll-theme-minimal
title: Esra Durmaz Mitchell, PhD
description: [Postdoctoral Research Associate @Â University of Fribourg, Switzerland]

twitter_username: durmaz_es
github_username : esradm
